test_ucounter16:
	ncverilog ucounter16_tb.v ucounter16.v +access+r

test_ucounter8:
	ncverilog ucounter8_tb.v ucounter8.v +access+r

clean:
	rm -f a.out ucounter16_tb.vcd
	rm -f a.out ucounter16_tb.fsdb
	rm -f a.out ucounter8_tb.vcd
	rm -f a.out ucounter8_tb.fsdb
    
