test_ucounter16:
	ncverilog ucounter16_tb.v ucounter16.v +access+r	

test_ucounter8:
	ncverilog ucounter8_tb.v ucounter8.v +access+r

clean:
	rm ucounter16_tb.vcd
	rm ucounter8_tb.vcd
	rm ucounter16_tb.fsdb
	rm ucounter8_tb.fsdb
    
