test_ucounter16:
	iverilog ucounter16_tb.v ucounter16.v	
	./a.out
	gtkwave ucounter16_tb.vcd

test_ucounter8:
	iverilog ucounter8_tb.v ucounter8.v
	./a.out
	gtkwave ucounter8_tb.vcd

clean:
	rm -f a.out ucounter16_tb.vcd
	rm -f a.out ucounter8_tb.vcd
    
